
language: kotlin
sudo: false # route the build to the container-based infrastructure for a faster build

jdk:
  - oraclejdk8

before_install:
  - "chmod +x gradlew"

script:
  - "./gradlew test"

notifications:
  email:
    - christoph.pickl@gmail.com

# avoid re-downloading dependencies all the time: https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
