logging:
  level:
    root: WARN
    com.github.christophpickl.payconiq: INFO
  file: payconiq-app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %X{userId} %X{requestId} %logger{36} - %msg%n"
